### ISSUE TITLE
The status in block is INTULocationStatusTimedOut but the currentLocation  is correct

### ISSUE THREAD

**Issue by aimm** [intuit/LocationManager#101]
NSLog(@"lat:%@,log:%@",@(currentLocation.coordinate.latitude),@(currentLocation.coordinate.longitude));
        
        if (status == INTULocationStatusSuccess)
        {
            // 更新用户坐标
            [kUser setLatitude:currentLocation.coordinate.latitude];
            [kUser setLongitude:currentLocation.coordinate.longitude];
            [kUser synchro];
            
            // 获取当前地区id、名称
            [self getCurrentAreaWithLatitude:@(currentLocation.coordinate.latitude)
                                   longitude:@(currentLocation.coordinate.longitude)];
        }
        else if (status == INTULocationStatusTimedOut)
        {
            [HUDManager showSystemAlertInVC:self title:@"提示" message:@"定位超时" cancelBtnTitle:@"确定" cancelBtnClickedBlock:nil];
        }
        else
        {
            [HUDManager showSystemAlertInVC:self title:@"提示" message:@"定位失败" cancelBtnTitle:@"确定" cancelBtnClickedBlock:nil];
        }

the log is correct but the status is timeout

**Comment by lwdupont** [comment]
Please give the latest release a try.
