### ISSUE TITLE
Showing alert with no user description if no NSLocationAlwaysUsageDescription

### ISSUE THREAD

**Issue by Dalein** [intuit/LocationManager#105]
In my .plist file I have NSLocationWhenInUseUsageDescription but when alert with location request appears - there 's no user description there. 

in this code:

  BOOL hasAlwaysKey = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationAlwaysUsageDescription"] != nil;
        BOOL hasWhenInUseKey = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationWhenInUseUsageDescription"] != nil;

I see that hasWhenInUseKey = true and [[NSBundle mainBundle] objectForInfoDictionaryKey:@"NSLocationWhenInUseUsageDescription"] is equal empty string.

Only if I add NSLocationAlwaysUsageDescription I can see description in this alert.

**Comment by Dalein** [comment]
@lwdupont my bad, I didn't know about InfoPlist.strings in which was a NSLocationWhenInUseUsageDescription = ""

**Comment by lwdupont** [comment]
No worries. Thanks for replying back 👍
