### ISSUE TITLE
Define time interval when subscribing to continuous location updates in background

### ISSUE THREAD

**Issue by prgorasiya** [intuit/LocationManager#109]
I would like to know whether I can define an interval at which I can get continuous location updates in background mode.
Currently, that time interval is about 15 secs but I would like to make it 5 secs.

Here is my code

```
requestID = backgroundLocationManager.subscribeToLocationUpdates(withDesiredAccuracy: .room) { (location, accuracy, status) in
            if status == INTULocationStatus.success{
                print(location as Any)
            }
}
```
Any help with that?

Thanks

**Comment by lwdupont** [comment]
No there is no way to do that now. Right now you'll get a callback when the location changes. 

Why would you want to get the location at a fixed interval of time?

**Comment by prgorasiya** [comment]
Basically my app's purpose is based on sending user's location every 10 seconds to my backend.
I saw that you have included this task in next release, may I know when will you be releasing that version and how to use this feature?
Thanks

**Comment by lwdupont** [comment]
Ah, got Ya. It would be better for you to do something like this in your code:

1. Subscribe to location changes with this library
2. Keep the last location that it sent you
3. Send that 'currentLocation' every 10 seconds.
