### ISSUE TITLE
Some way to control activityType

### ISSUE THREAD

**Issue by sameer4** [intuit/LocationManager#120]
My current application isn't achieving a good horizontalAccuracy...

I know GPS accuracy is highly dependent on location and the environment 

but i was looking for ways to improve it. and from [here](https://stackoverflow.com/questions/55551981/how-the-get-a-higher-gps-accuracy-in-ios-12)

they recommended to set the activity type to .fitness, and there isn't a way to control activityType from library

**Comment by dcortright** [comment]
I would like to pick this task up if that is okay?

**Comment by lwdupont** [comment]
@dcortright For sure, thank you!

**Comment by dcortright** [comment]
Thanks! Can I get this assigned to me and the Hacktoberfest label added?

**Comment by lwdupont** [comment]
Done :)

**Comment by dcortright** [comment]
@lwdupont not sure if you are the right person to tag for this, but here is my pull request: https://github.com/intuit/LocationManager/pull/123

**Comment by lwdupont** [comment]
Thanks! Will review more today sometime. 👍

**Comment by lwdupont** [comment]
Fixed with pr#124
