### ISSUE TITLE
Hi! I see that `auto version` return the semantic version bump, but is there a way to get the next (release) version with that bump applied? I think it would be very useful in non-standard release workflows that want to call atomic `auto` commands instead of relying on the complex ones like `shipit`.

### ISSUE THREAD

**Issue by Emiliano978** [intuit/LocationManager#135]
Hi! I see that `auto version` return the semantic version bump, but is there a way to get the next (release) version with that bump applied? I think it would be very useful in non-standard release workflows that want to call atomic `auto` commands instead of relying on the complex ones like `shipit`.

_Originally posted by @laughedelic in https://github.com/intuit/auto/discussions/1867_

**Comment by laughedelic** [comment]
Are you testing the export functionality from discussion comments to issues?

**Comment by lwdupont** [comment]
Seems like it’s not set up right. 😂
