### ISSUE TITLE
[feature] Knowing the user general location without asking for permission.

### ISSUE THREAD

**Issue by sSegev** [intuit/LocationManager#2]
A nice feature to have in this class is the ability to identify the user general location (country) without asking for permission. Something like a `desiredAccuracy` of `INTULocationAccuracyCountry`. This can be done in a number of ways but the best I can think of is to use something like http://www.iplocationtools.com/ or any other free service that offers to translate an IP address to a country. (And of course without using Core Location)

Services like Spotify etc' that are country based always using something like that in order to know the user location without asking for permission.

**Comment by Ricardo1980** [comment]
I disagree. I mean, if user doesn't give you permission for location, well, it's because he doesn't want to located. Why do you want to bypass his/her decision?

**Comment by fabiocaccamo** [comment]
Do you think that google analitycs doesn't geocode your ip address? :)

**Comment by GabrielCartier** [comment]
The library is basically an API for Apple's SDK. Not sure how getting the location through geocoding has anything to do with this.

**Comment by DDany** [comment]
+1

**Comment by callzhang** [comment]
@Ricardo1980 In our app we need at least knowing user's timezone in order to provide time related service.

**Comment by Ricardo1980** [comment]
@callzhang Timezone and location are 2 different things. And you can get time zone always you want, you don't have to ask for permission. http://stackoverflow.com/questions/19186666/get-timezone-country-from-iphone

**Comment by iwasrobbed** [comment]
If you already use Google Maps, you can accomplish this by piggybacking off of their `myLocation` property on the map view class.

**Comment by kristinathai** [comment]
This is probably something that will never get implemented for INTULocationManager. As @iwasrobbed suggested, there are other ways to accomplish this. Thanks for the suggestion.

**Comment by nirapanchal-multipz** [comment]
Hello, How are you????
