### ISSUE TITLE
Unknown type name 'CGFloat'

### ISSUE THREAD

**Issue by KevinIsSun** [intuit/LocationManager#21]
When i pod update and build, i failed and get the message "unknown type name 'CGFloat'" in INTULocationDefines.h. I don't know how to fix it, ty.
The problem code is: static const CGFloat kINTUHorizontalAccuracyThresholdCity =         5000.0; 

I fix the bug when i add "~>1.0" in my podfile. But why it didn't work in 2.0.0 version?

**Comment by smileyborg** [comment]
Hey, thanks for reporting this!

v2.0.0 changed how some of these constants are defined. I've made a change so that `<Foundation/Foundation.h>` is now imported at the top of that file, which should fix the issue. Can you please try updating to the latest pod version (v2.0.1) and seeing if the issue is resolved?

**Comment by KevinIsSun** [comment]
Thank you for watching this issue, I resolve the issue by updating. Maybe I can say "thanks" in chinese. 谢谢 :-)

**Comment by smileyborg** [comment]
👍 You're welcome!

**Comment by KevinIsSun** [comment]
Maybe u need reopen the issue. I find I fix the bug not because updating, the real reason is that I add a pch file in my project. And i add "#include <UIKit/UIKit.h>" in the file. So if I want to use the library, I must add a pch file? Apple remove pch file in Xcode6 project template which means I must add it by manual.

**Comment by smileyborg** [comment]
You do not need a PCH file to use INTULocationManager. I just tested creating a new project using Xcode 6, and adding just the INTULocationManager pod, and the project builds & runs successfully.

There must be an issue with your specific build configuration that is causing the problem...I would suggest trying to remove your PCH file, and then doing a full Clean/Clean Build Folder (and/or just delete the DerivedData folder for your Xcode Workspace). Then try building again.

There shouldn't be any changes required to the INTULocationManager pod to fix this.

**Comment by KevinIsSun** [comment]
I success after delete DerivedData, don't notice it before. Thanks a lot for ur help.
