### ISSUE TITLE
bug while using library

### ISSUE THREAD

**Issue by Ne3maRayan** [intuit/LocationManager#24]
To use location services in iOS 8+, your Info.plist must provide a value for either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription.

**Comment by DDany** [comment]
@Ne3maRayan , I don't think this is a bug. It's quite necessary.
Such as, PJSIP lib (VoIP call) want you to set background mode yourself in Info.plist.

**Comment by smileyborg** [comment]
Hi @Ne3maRayan,

This is not a bug. Please read this section of the README and let me know if you have any additional questions: https://github.com/intuit/LocationManager#requesting-permission-to-access-location-services

Thanks!
