### ISSUE TITLE
Better location services availability reporting

### ISSUE THREAD

**Issue by pronebird** [intuit/LocationManager#29]
Hi,

As you know since iOS 8 we are able to open privacy settings directly via openURL. So to avoid frustration developers now can display instructions how to enable location services whether system or app wide and basically take user to privacy settings in latter case. 

It would be great to add methods that could report current status of authorization granted to the app or whether location services are disabled on device.

Would it be possible to adapt code below for INTULocationManager and would you like to include such methods in your Pod?

```objc
@implementation INTULocationManager (AuthorizationStatus)

// whether location services are enabled on device
// e.g. I use it show alert to user that explains how to open settings and flip that switch
+ (BOOL)locationServicesEnabled {
    return [CLLocationManager locationServicesEnabled];
}

// whether first time permissions request was sent
// Usually I use it in combination with authorizedForLocationServices to understand 
// whether I should show instructions on how to enable location services 
// in case when user denied access in the first place.
+ (BOOL)shouldRequestAuthorization {
    return ([CLLocationManager authorizationStatus] == kCLAuthorizationStatusNotDetermined);
}

// whether app is authorized to use location services
+ (BOOL)authorizedForLocationServices {
    CLAuthorizationStatus authorizationStatus = [CLLocationManager authorizationStatus];
    return (authorizationStatus == kCLAuthorizationStatusAuthorizedAlways || authorizationStatus == kCLAuthorizationStatusAuthorizedWhenInUse);
}

@end
```

Thanks you.

**Comment by smileyborg** [comment]
Hi Andrej,

Thanks for the suggestion. This is actually quite similar to #28. I haven't had time to consider that one carefully yet, but would love to hear your thoughts...how would you like to see your suggested changes reconciled with that PR?

I'm always in favor of a simpler public API...that's the main reason why INTULocationManager exists in the first place. So, I'd like to expose the minimum necessary. Instead of 3 or 4 methods, perhaps one that returns an enum value like `INTULocationStatus` (assuming the possibilities are mutually exclusive)?

It would probably be good for us to list out the potential things a developer using INTULocationManager would want to know regarding permissions/authorization/etc.

Let me know what you think.

**Comment by pronebird** [comment]
Hi Tyler, I think that would be great, both requests are similar.

**Comment by smileyborg** [comment]
OK, thanks for the patience on this :)

Here's what I propose:

1. The following existing API on INTULocationManager will be **deprecated** for now, and removed in a future release:

        /** Returns YES if location services are enabled in the system settings, and the app has NOT been denied/restricted access. Returns NO otherwise. */
        @property (nonatomic, readonly) BOOL locationServicesAvailable;

2. The proposals in this PR (#29) and the related issue raised by @pronebird (#28) will be consolidated by adding a single new public API:

        /** Returns the current state of location services for this app, based on the system settings and user authorization status. */
        + (INTULocationServicesState)locationServicesState;

    This API is a class method (as opposed to a readonly property) because we don't need an instance of INTULocationManager to return the current state.

    Here is the definition of the return type `INTULocationServicesState`:

```
/** The possible states that location services can be in. */
typedef NS_ENUM(NSInteger, INTULocationServicesState) {
    /** User has already granted this app permissions to access location services, and they are enabled and ready for use by this app.
        Note: this state will be returned for both the "When In Use" and "Always" permission levels. */
    INTULocationServicesStateAvailable,
    /** User has not yet responded to the dialog that grants this app permission to access location services. */
    INTULocationServicesStateNotDetermined,
    /** User has explicitly denied this app permission to access location services. (The user can enable permissions again for this app from the system Settings app.) */
    INTULocationServicesStateDenied,
    /** User does not have ability to enable location services (e.g. parental controls, corporate policy, etc). */
    INTULocationServicesStateRestricted,
    /** User has turned off location services device-wide (for all apps) from the system Settings app. */
    INTULocationServicesStateDisabled
};
```

As I had previously suggested, this API/enum somewhat mirrors the `INTULocationStatus` one that is used when executing the block for a location request. The difference of course is that this `INTULocationServicesState` does not correspond to a specific location request and can be queried at any time (such as before even making the first location request).

I like this proposal for two main reasons:
 * it's simple, with just a single public API (as opposed to a few new methods that each return a BOOL)
 * it uses an enum to capture all the states, which makes it clear that they are mutually exclusive and that only one is possible at any given time

Please let me know if this addresses everything you have in mind, and if you have any suggestions for improvement. I'll get this checked in if all is good!
