### ISSUE TITLE
Slow Location Results

### ISSUE THREAD

**Issue by chadwilken** [intuit/LocationManager#30]
I request the user's location on app launch it it sometimes takes several minutes to get the location. I am in the middle of the city and other apps are working just fine with location. Have you hit this issue before and is it library related?

**Comment by smileyborg** [comment]
Hey Chad,

If you find that it's taking a long time to get the location back using INTULocationManager, you are probably requesting a very high accuracy level (e.g. `INTULocationAccuracyRoom`). If you do want a very accurate location that's fine, but you should include a `timeout` value that reflects how long you are willing to wait (e.g. 10 seconds). Then, even if INTULocationManager isn't able to get a super-accurate location as you request, it will still return the most accurate location it was able to obtain in the time you gave it.

Of course, be sure to only request the accuracy level that you actually need. If for example you are just trying to determine the user's current city for a weather app, for example, then be sure to just request City-level accuracy!

Please let me know if that isn't clear or if you're seeing a specific issue.
Thanks!

**Comment by chadwilken** [comment]
That did it for me. Thanks for the clarification on the timeout still giving it's best accuracy.
