### ISSUE TITLE
Fail to build a project with the library. Compiling a project results compiler complaining the GCFloat is unknown

### ISSUE THREAD

**Issue by dgutzeit** [intuit/LocationManager#32]
Added the pod using cocoapods, can not build the project.
What helps is adding importing UIKit/UIKit.h into INTULocationRequestDefines

**Comment by smileyborg** [comment]
Hey Dima,

Thanks for bringing this up. You're right, the problem is actually that `CGFloat` is the wrong type for these values. (We don't want to import UIKit since this library doesn't use it.)
