### ISSUE TITLE
Bug when requesting permissions

### ISSUE THREAD

**Issue by walteryaron** [intuit/LocationManager#38]
When requesting permissions from user the alert popup show for 1 seconds and then disappear
When i implement in Apple regular code the alert popup doesn't disappear

**Comment by smileyborg** [comment]
Hi @walteryaron,

Thanks for reporting this. I have not seen this issue myself, or heard of any other reports of it.

Can you reproduce the issue using the example project in this repo? What version of iOS are you running on?

You'll need to provide more info, and preferably a sample project to reproduce the issue, if you'd like help debugging it.

**Comment by walteryaron** [comment]
Hi
I will create sample project.
Thanks

**Comment by smileyborg** [comment]
@walteryaron Any updates on this?

**Comment by walteryaron** [comment]
Not related to this project
Sorry
