### ISSUE TITLE
can add two blocks for the location request 

### ISSUE THREAD

**Issue by AndyChenW** [intuit/LocationManager#40]
start and finish of the location request, one basic usage will be the location request time spent tracking by these hooks.

**Comment by smileyborg** [comment]
Hey Andy, I'm not sure what you mean here, can you please clarify? Is this a feature request or an issue/problem?

**Comment by AndyChenW** [comment]
Hi @smileyborg feature. Can we add two hooks for location started and location ended?

**Comment by smileyborg** [comment]
I'm still not sure I understand. I don't really see the use case for tracking the time of the location request, but it's easy to do today by simply storing the start time when you begin the request, and then comparing the current time to the start time when the block executes.

**Comment by smileyborg** [comment]
Perhaps you can give a concrete example of what you need to do, and/or what the public API would look like?

**Comment by smileyborg** [comment]
Closing this for now, please see questions above if you still feel this issue is valid.
