### ISSUE TITLE
Does this lib support CLHeading?

### ISSUE THREAD

**Issue by Ricardo1980** [intuit/LocationManager#41]
Does this lib support CLHeading?
I want to create a compass that points to a location (not to the north), so apart from the current location I need the current heading.
Otherwise, any recommendation of another location manager?
Thanks in advance!

**Comment by smileyborg** [comment]
INTULocationManager does not support heading. You can use Core Location (CLLocationManager) directly for this.

There was also a pull request to add heading support to this project, but unfortunately the initial implementation had some issues and the developer did not respond to address them. Regardless, it is definitely a good starting point: https://github.com/intuit/LocationManager/pull/22

**Comment by Ricardo1980** [comment]
I don't see it. Can you tell me the address?
Apart from that, any suggestion in order to add that feature? What was the mistake added in that time?

**Comment by smileyborg** [comment]
Please click on the link to view PR #22. The discussion there covers everything you are asking about.
