### ISSUE TITLE
Crash because of changing array while iterating over it

### ISSUE THREAD

**Issue by oonoo** [intuit/LocationManager#46]
When i use the lib it crashes, it crashes in the processLocationRequests method in the for-loop. The error is the mutation of the array self.locations and at the same time using self.locations in this loop. I fixed it by making a copy of self.locations and use this copy for the loop:

    NSArray *locationRequests = [self.locationRequests copy];
    for (INTULocationRequest *locationRequest in locationRequests) {
    ...

**Comment by smileyborg** [comment]
Hi @oonoo,

Thanks for reporting this. Can you share more details about the crash you're experiencing? Are you able to provide steps to reproduce this?

If you take a look at [INTULocationManager.m Line 341](https://github.com/intuit/LocationManager/blob/master/LocationManager/INTULocationManager/INTULocationManager.m#L341), we're already using a separate array to collect completed requests, aside from the `self.locationRequests` array, to avoid this problem.

The only code path I can see that would be potentially problematic is if you are starting or canceling location requests **from within** a subscription block.

I want to make sure that I understand exactly how you're running into this crash before applying a fix for it.

Thanks!

**Comment by smileyborg** [comment]
@oonoo Any updates on this?

**Comment by smileyborg** [comment]
I've made some changes in c2913e2 that should resolve this issue. I would still appreciate more details to make sure that this does indeed address the root cause.

At the very least, please confirm that this commit does fix the crash/exception you were seeing.

Thanks!
