### ISSUE TITLE
No background updates?

### ISSUE THREAD

**Issue by Bamsoo** [intuit/LocationManager#49]
Hi there,

Thanks for this library. `subscribeToLocationUpdatesWithDesiredAccuracy` you introduced recently is a long-awaited and great feature.

I'm subscribing to desired accuracy update in  `didFinishLaunchingWithOptions` app delegate. `NSLocationAlwaysUsageDescription` is set in the property list and  location updates is activated in background modes.

I opted in to receive location updates even in background. But, when the app goes to the background, I no longer receive updates, with no further log. As soon as it is in the foreground I get them back.

What did I miss? Does background mode only work with `subscribeToSignificantLocationChangesWithBlock`?

Thanks for your help.

**Comment by Bamsoo** [comment]
Setting `allowsBackgroundLocationUpdates` to `true` on the location manager now seems mandatory when linking against iOS9, to enable background updates. Mentioned [here](http://stackoverflow.com/questions/30808192/allowsbackgroundlocationupdates-in-cllocationmanager-in-ios9).

**Comment by smileyborg** [comment]
Thanks for reporting this! This is definitely something that needs to be addressed, there is an attempt in #57 to do so.
