### ISSUE TITLE
Can you please new version , 4.0 , doesn't have significantLocationChanges

### ISSUE THREAD

**Issue by pavankris** [intuit/LocationManager#50]
Can you please release new version , 4.0 , doesn't have significantLocationChanges

**Comment by pavankris** [comment]
please release new version * - sorry for the typo.

**Comment by mwapptest** [comment]
Yes its not there...

**Comment by Bamsoo** [comment]
Until fixed, you can get the flavour of the new features by specifying a given commit in you pod file, like:
`pod 'INTULocationManager', :git => "https://github.com/intuit/LocationManager.git", :commit => '930ae1551829e026984fe631756df17c4a32f9ca'`
Temporary workaround, of course.

**Comment by pavankris** [comment]
Yeah i understand, but dont want to do the above fix. , really messy .

**Comment by smileyborg** [comment]
A new version will be released within a couple weeks, including the latest code and APIs. If you wish to test and use the unreleased changes until then, please use the method described above by @Bamsoo.

**Comment by pavankris** [comment]
:+1:

**Comment by kristinathai** [comment]
I just released v4.1.0 that includes the latest changes. Enjoy! :octocat:
