### ISSUE TITLE
INTULocationManager crash App in Simulator

### ISSUE THREAD

**Issue by tenaz3** [intuit/LocationManager#51]
Well when run app in xcode7 (ios 9.0/swift 2) works normally. But if I run just in iOS simulator the app crashes.

**Comment by sunkehappy** [comment]
Could you supply more details (like any crash log? what `LocationManager` version are you using)? Because I could not reproduce it on my local machine.

**Comment by tenaz3** [comment]
Unfortunately I downgrade my xcode, because broke all my code. I don't have the log any more
Version:
 pod 'INTULocationManager', '~> 4.0'

**Comment by smileyborg** [comment]
Hi @tenaz3,

Are you still experiencing this crash? As @sunkehappy requested, we'll need more details to help debug the issue you're seeing. Specifically, if you can provide details on the Xcode version, iOS Simulator version, and INTULocationManager version that can reproduce this crash. A crash log and any other details would also help.

If we cannot reproduce the crash and you don't have any other details to share, then we won't be able to help.
