### ISSUE TITLE
INTULocationManagerVersionNumber

### ISSUE THREAD

**Issue by MickeyHub** [intuit/LocationManager#53]
why exists INTULocationManagerVersionNumber and INTULocationManagerVersionString ,
but not be used in file `INTULocationManager.h` line:29

**Comment by smileyborg** [comment]
Hi @MickeyHub,

These are constants that exist in every umbrella header of a dynamic framework. If you create a new dynamic framework target in Xcode, you will see these placed in the umbrella header. You can simply ignore them as a user of this library.
