### ISSUE TITLE
INTULocationAccuracy

### ISSUE THREAD

**Issue by MickeyHub** [intuit/LocationManager#55]
why not corresponding to system LocationAccuracy?

**Comment by smileyborg** [comment]
Please take some time to read through the README as well as the comments and documentation in the code for INTULocationAccuracy. You'll see that these constants represent both *horizontal accuracy* **and** *recency*. The Core Location types do not do this. Additionally, INTULocationAccuracy is designed to be more friendly to use instead of having to think in terms of meters.

**Comment by salvoc** [comment]
What would be the best way for changing the predefined constants in my projects? for example making the INTULocationAccuracyHouse be 10 metres in the last 15 seconds?

**Comment by smileyborg** [comment]
@salvoc This is not supported; there's no way to do this using INTULocationManager, without effectively forking the code to make changes. Which is an option if you absolutely must have a very particular configuration, but I think this is extremely unlikely.

Feel free to share more details if you think there is a very compelling reason to support this. But don't forget that this library is designed to solve 90-95% of location services use cases well with an extremely simple API...there will always be the remaining 5-10% of advanced use cases that are explicitly not within the scope of this project and should be tackled with other approaches.

**Comment by salvoc** [comment]
Thanks for your response @smileyborg, I believe that adding the opportunity of fine tuning that feature would be a great enhancement, still maintaining of course a default scale for simple use cases.

**Comment by salvoc** [comment]
Is that ok for you if I fork the project, add that functionality and create a new public Pod for that?

**Comment by smileyborg** [comment]
@salvoc By all means feel free to fork over his project and make your own changes! If you think you can do so in a way that would be beneficial to everyone you can open a pull request here. But if you know they will be intended to solve a different set of use cases feel free to publish a new pod.
