### ISSUE TITLE
The block never gets called

### ISSUE THREAD

**Issue by rezasham** [intuit/LocationManager#62]
It was working fine, but at some point it just started not to call the block any longer. I can´t even look at the status value. I only get these in the log:

INTULocationManager: Changing location services accuracy level to: medium.
INTULocationManager: Location services updates have started.
INTULocationManager: Location Request added with ID: 1

I have tested calling it once:

[locMgr requestLocationWithDesiredAccuracy:INTULocationAccuracyBlock
                                           timeout:10.0
                              delayUntilAuthorized:YES  // This parameter is optional, defaults to NO if omitted
                                             block:^(CLLocation *currentLocation, INTULocationAccuracy achievedAccuracy, INTULocationStatus status);

Testing on device with IOS 9.1. Also have added the necessary key in info.plist to get authorization. Using latest released version 4.1.1 (also 4.0.0).

Any ideas what may be wrong?

**Comment by rezasham** [comment]
What I found out was that the code needs to run on the main thread. I was calling it on global queue with high priority though.

**Comment by kristinathai** [comment]
@rezasham Glad you figured it out. I added some assertions to make it clear for future developers. Thanks!
