### ISSUE TITLE
对于中国移动网络支持不足

### ISSUE THREAD

**Issue by lovecrossyou** [intuit/LocationManager#66]
中国移动网络经常定位超时

**Comment by lwdupont** [comment]
Do you mind reposting in English? Thanks. (I don't trust google translate :)

**Comment by vinner2112** [comment]
Hey friend, 

I've  just found something  really strange but at  the  same time  interesting, I think it is worth seeing, just take a look <http://postal.dropsoldship.com/e4egso>

Sincerely yours, vinner_2112
