### ISSUE TITLE
Location Request message disappears

### ISSUE THREAD

**Issue by lfarah** [intuit/LocationManager#68]
[The Location Request message disappears because of this problem](http://stackoverflow.com/questions/7888896/current-location-permission-dialog-disappears-too-quickly#9474095)

**Comment by natalia-osa** [comment]
The class is a singleton and location manager is a private strong property inside, which is set only once. I can't imagine situation, where it is released. Maybe I didn't notice something, but what makes you think this is the issue?

**Comment by lwdupont** [comment]
Please let us know if it's still an issue. I had a look at the code just now and can't see how it might have gotten disposed of.
