### ISSUE TITLE
No option to set pausesLocationUpdatesAutomatically to NO.

### ISSUE THREAD

**Issue by Gnative** [intuit/LocationManager#70]
This is causing a break in my application running in the background where location updates don't restart after being paused in background mode by pausesLocationUpdatesAutomatically.

**Comment by oliverfoggin** [comment]
I was just about to ask this also. The iOS9 background mode check doesn't update this property.

**Comment by 4Kicks** [comment]
Folks, I'd like to understand this issue more as this is new to me.  So despite setting the background mode in Capabilities section, this property must now also be set?  Just wanting to confirm that this isn't some bug introduced in iOS 9.

**Comment by Gnative** [comment]
It might be a bug in ios9 but either way i need to be able to disable this by setting it to "No" as my application needs to be able to run in the background continuously. Current with this enabled if you stop for any length of time the location manager pauses updates (and powers down the appropriate hardware). If the application is in the background the location updates do not resume until or unless the application is in the foreground again.

**Comment by oliverfoggin** [comment]
Looking at this... https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html#//apple_ref/doc/uid/TP40009497-CH2-SW10

It looks like the location hardware is turned off and updates paused when the user isn't moving. This property being set to yes allows this to happen to conserve battery.

Hmm... maybe my decision to set it to no was mistaken.

**Comment by Gnative** [comment]
Depends if you want your app to run continuously in the background, it will stop location updates if someone stands still for a period of time.

**Comment by 4Kicks** [comment]
@Gnative I would currently recommend forking this repo and making this change internally for your needs since you are currently being impacted by this issue.

I found the same discussion that @oliverfoggin did on the pausesLocationUpdatesAutomatically property and while you may still have a legitimate reason to change this behavior, I think it's important to do a bit more poking around to understand this property better.

**Comment by dustturtle** [comment]
I think it is important for background locating apps. If set YES, you may not run continuously in background. @Gnative @oliverfoggin @4Kicks @lwdupont

**Comment by lwdupont** [comment]
@dustturtle I'll dig some more into it and let you know my thoughts. But sure seems like the library should have an api to allow users to flip it.

**Comment by dustturtle** [comment]
Thank you so much for the great work around this！

**Comment by harri121** [comment]
Any updates on this?

**Comment by lwdupont** [comment]
Thanks to @danielkiedrowski for the pull request. I just released 4.3.0 with his change.
