### ISSUE TITLE
INTULocationStatus == INTULocationStatusError if network connection is lost

### ISSUE THREAD

**Issue by eckert** [intuit/LocationManager#77]
I want to retrieve departure locations for car trips even if a trip starts in an underground parking where it might take a couple of time until an acceptable location is available...
I am using requestLocationWithDesiredAccuracy: with a timeout of 120 seconds because  I recognized that if I am losing the network connection then the block is called immediately with INTULocationStatus == INTULocationStatusError (before timeout period is expired).

**Comment by mobiledevelopment2015** [comment]
I recognized that the CLLocationManger delegate method didFailWithError is called with error.code 0 and error.domain kCLErrorDomain as soon as the network connection is lost. This results in calling [self completeLocationRequest:locationRequest]; even if the locationRequest has not timed out. A very basic solution could be to check against timeout expiration and error:

if (!locationRequest.hasTimedOut && error.code == 0 && [error.domain isEqualToString:kCLErrorDomain])
        {
            // Keep the request alive if locationRequest has not timed out.
            INTULMLog(@"Location services error with error_code 0: %@", [error localizedDescription]);
        }

as example in didFailWithError:

- (void)locationManager:(CLLocationManager *)manager didFailWithError:(NSError *)error
{
    INTULMLog(@"Location services error: %@", [error localizedDescription]);
    self.updateFailed = YES;

    for (INTULocationRequest *locationRequest in self.locationRequests) {
        if (!locationRequest.hasTimedOut && error.code == 0 && [error.domain isEqualToString:kCLErrorDomain])
        {
            // Keep the request alive if locationRequest has not timed out.
            INTULMLog(@"Location services error with error_code 0: %@", [error localizedDescription]);
        }
        else
        {
            if (locationRequest.isRecurring) {
                // Keep the recurring request alive
                [self processRecurringRequest:locationRequest];
            } else {
                // Fail any non-recurring requests
                [self completeLocationRequest:locationRequest];
            }
        }
    }
}
