### ISSUE TITLE
2 instance of INTULocationManager

### ISSUE THREAD

**Issue by Berdikhan** [intuit/LocationManager#83]
Hi, thanks for great library.

Any idea how to have 2 instance of LocationManager, I need to subscribe for significant and most accurate location updates, because significant subscription helps me to wake up after termination/suspension of the app. 

Current implementation has conflicts between 2 subscriptions.

Thanks

**Comment by iwasrobbed** [comment]
@Berdikhan The basis behind INTULocationManager was to have one singleton that managed many types of subscriptions, doing away with the old way of creating multiple instances of a location manager that you'd need to start/stop.

What is preventing you from making two different subscriptions, one for higher energy and one for low energy (significant) updates? 

>Current implementation has conflicts between 2 subscriptions.
