### ISSUE TITLE
Background location

### ISSUE THREAD

**Issue by cordeiroigor** [intuit/LocationManager#89]
I did the following:
    func StartService(context: NSManagedObjectContext?){
        contextP = context
        let loc = INTULocationManager.sharedInstance()

        loc.subscribeToLocationUpdates(withDesiredAccuracy: .block, block: {(currentLocation: CLLocation?,
            achievedAccuracy: INTULocationAccuracy,
            status: INTULocationStatus) -> Void in
            if (currentLocation != nil){
                print(self.LOG + "Request " + String(describing: NSDate()))
               self.RequestPosition()
            }
        })
    }
However when I kill the application it to send you sending the positions, what should I do so this does not happen?

**Comment by lwdupont** [comment]
Old, closing. Presumably you've worked through it by now?
