### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by thewildcloud** [intuit/LocationManager#9]
Hi, 

I am new to iOS programming. As I added the Source files onto my Xcode project, i encountered the following errors when compiling. Any suggestions?

Undefined symbols for architecture x86_64:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CLLocationManager", referenced from:
      objc-class-ref in INTULocationManager.o
  "_kCLLocationAccuracyBest", referenced from:
      -[INTULocationManager startUpdatingLocationIfNeeded] in INTULocationManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by shaobo8910** [comment]
Assertion failure in -[INTULocationManager startUpdatingLocationIfNeeded], /Users/andrew/Documents/workspace/flint/code_0605/YYPro/src-app/app/libraries/INTULocationManager/INTULocationManager.m:299


what's wrong? please help! thanks ...

**Comment by smileyborg** [comment]
@shaobo8910 You are hitting the assertion here: https://github.com/intuit/LocationManager/blob/master/LocationManager/INTULocationManager/INTULocationManager.m#L299

Please read this section of the README: https://github.com/intuit/LocationManager#ios-8
