### ISSUE TITLE
the manager always  time out

### ISSUE THREAD

**Issue by MrNAVY** [intuit/LocationManager#91]
when i use the manager it always time out
[[INTULocationManager sharedInstance] requestLocationWithDesiredAccuracy:INTULocationAccuracyHouse timeout:10 block:^(CLLocation *currentLocation, INTULocationAccuracy achievedAccuracy, INTULocationStatus status) {
        [SVProgressHUD dismiss];
        [SVProgressHUD showWithStatus:@"正在搜索附近的设备"];
        //获取状态成功
        if (status == INTULocationStatusSuccess) {
            [LCBaseRequest getResultWithUrl:@"api/mobile/getNearbyLocks" param:@{@"lng":@(currentLocation.coordinate.longitude),@"lat":@(currentLocation.coordinate.latitude)} resultClass:[NearbyLockModel class] success:^(NSArray<NearbyLockModel *> *result, ResponseModel *responseModel) {
                [SVProgressHUD dismiss];
                weakself.dataSource = [result mutableCopy];
                [weakself.tableView.mj_header endRefreshing];
                [weakself.tableView reloadData];
            } failure:^(NSString *error) {
                [weakself.tableView.mj_header endRefreshing];
                [SVProgressHUD showErrorWithStatus:error];
            }];

        }else if (status == INTULocationStatusServicesDisabled)
        {
            [weakself.tableView.mj_header endRefreshing];
            [SVProgressHUD showErrorWithStatus:@"系统未打开定位"];
        }else if (status == INTULocationStatusServicesDenied)
        {
            [weakself.tableView.mj_header endRefreshing];
            [SVProgressHUD showErrorWithStatus:@"系统未授权使用定位功能"];
        }else{
            [weakself.tableView.mj_header endRefreshing];
            [SVProgressHUD showErrorWithStatus:@"定位失败"];
        }
    }];

**Comment by lwdupont** [comment]
I believe others have reported this too - like iOS isn't refreshing the location within the time that the LocationManager sets. 

It's hard for me to understand that code you pasted above, but I believe it's a known issue.

**Comment by MrNAVY** [comment]
it is about DesiredAccuracy,when i use the INTULocationAccuracyHouse,it will failure ,but it can work when the DesiredAccuracy is INTULocationAccuracyBlock

**Comment by lwdupont** [comment]
See my comment on #87
