### ISSUE TITLE
iOS 11 - Updating location in background stopped working

### ISSUE THREAD

**Issue by mhergon** [intuit/LocationManager#95]
Hi,

After update my iPhone to iOS 11 `significantChanges` stopped reporting location updates. From iOS 11, only two or three location updates fired after driving 30 km.

I think that iOS 11 is more restrictive, but I tried with iOS 11.1 beta and problem still present.
Any help?

PS: on iOS 10 works fine

**Comment by selected-pixel-jameson** [comment]
@mhergon https://stackoverflow.com/questions/44424092/location-services-not-working-in-ios-11

**Comment by mhergon** [comment]
@selected-pixel-jameson nothing works!
On iOS 10 significatnChanges report location every few seconds in background mode, but on iOS 11 only 4 or 5 locations after 1 hour...

**Comment by juanroa01** [comment]
+1 for iOS 11 support using the new `NSLocationAlwaysAndWhenInUseUsageDescription` key in Info.plist.

**Comment by mrikh** [comment]
Is this fixed for iOS 11?

**Comment by mhergon** [comment]
@mrikh not for me.
In my case, I made my own framework: https://github.com/mhergon/EagleBit

**Comment by danielkiedrowski** [comment]
It is fixed now with pull request #99, but the version code hasn't been bumped so you have to link this git repository in your podfile to access the head.

`pod 'INTULocationManager', :git => 'https://github.com/intuit/LocationManager.git'`

**Comment by mhergon** [comment]
Ok, thanks!

**Comment by lwdupont** [comment]
Give the latest released version a try.
